require-license: false
require-known-license: false

allow:
  - MIT
  - BSD-3-Clause
  - BSD-2-Clause
  - Apache-2.0
  - ISC
  - 0BSD
  - LGPL-3.0-or-later
  - MPL-2.0
  - Python-2.0
  - BlueOak-1.0.0
  - CC0-1.0
  - Unlicense
deny:
  - GPL-3.0
  - AGPL-3.0

ignore-packages:
  - 'actions/*'
  - 'kod*'
